# Generated by Django 5.2.5 on 2026-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact5_share_distrib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyinterestpool',
            name='is_distributed',
        ),
        migrations.AddField(
            model_name='yearlyinterestpool',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='pending', max_length=20),
        ),
    ]
