# Generated by Django 5.2.5 on 2026-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact5_share_distrib', '0002_remove_yearlyinterestpool_is_distributed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyinterestpool',
            name='distribute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
