# Generated by Django 5.2.5 on 2026-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact5_share_distrib', '0003_yearlyinterestpool_distribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyinterestpool',
            name='not_distributed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
