# Generated by Django 5.2.5 on 2026-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact5_share_distrib', '0005_yearlyinterestpool_total_not_distributed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyinterestpool',
            name='distribute',
        ),
        migrations.RemoveField(
            model_name='yearlyinterestpool',
            name='not_distributed',
        ),
        migrations.AddField(
            model_name='memberinterestshare',
            name='distribute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='memberinterestshare',
            name='not_distributed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
