# Generated by Django 5.2.5 on 2026-05-30 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateTimeField()),
                ('backup_size_mb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backup_file', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-backup_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_FAILED', 'Login Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('PASSWORD_RESET', 'Password Reset'), ('PERMISSION_DENIED', 'Permission Denied'), ('ACCOUNT_LOCKED', 'Account Locked')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user'], name='system_moni_user_id_49d061_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['last_activity'], name='system_moni_last_ac_e3c3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['is_active'], name='system_moni_is_acti_560959_idx'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
