# Generated by Django 5.2.5 on 2026-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_accountstatement_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('loan_issued', 'Loan Issued'), ('loan_interest', 'loan-interest'), ('top_up', 'Loan Top-Up'), ('loan_payment', 'Loan Payment'), ('penalty_late_payment', 'Penalty - Late Payment'), ('penalty_underpayment', 'Penalty - Underpayment'), ('borrowing', 'Borrowing'), ('lending', 'Lending'), ('peer_loan_issued', 'Peer Loan Issued'), ('peer_loan_received', 'Peer Loan Received'), ('peer_loan_payment', 'Peer Loan Payment'), ('transfer', 'Transfer')], max_length=30),
        ),
    ]
