# Generated by Django 5.2.5 on 2026-01-21 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerBorrowingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.memberaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PeerLendingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.memberaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PeerToPeerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='peer_contracts/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_loans', to='accounts.memberaccount')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_loans', to='accounts.memberaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeerLoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='transact3_lending.peertopeerloan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
