# Generated by Django 5.2.5 on 2026-02-18 15:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0006_alter_loanpayment_due_date'),
        ('transact3_lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peerloanrepayment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='peerloanrepayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='peerloanrepayment',
            name='delay_time',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='peerloanrepayment',
            name='peer_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='transact3_lending.peertopeerloan'),
        ),
        migrations.AddField(
            model_name='peerloanrepayment',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peerloanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, help_text='Optional: link a regular Loan to enforce monthly schedule & penalties', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_repayments', to='transact2_loans.loan'),
        ),
    ]
