# Generated by Django 5.2.5 on 2026-02-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact3_lending', '0002_alter_peerloanrepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peerloanrepayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='peerloanrepayment',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='peerloanrepayment',
            name='delay_time',
        ),
        migrations.RemoveField(
            model_name='peerloanrepayment',
            name='peer_loan',
        ),
        migrations.RemoveField(
            model_name='peerloanrepayment',
            name='penalty_applied',
        ),
        migrations.AlterField(
            model_name='peerloanrepayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerloanrepayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='transact3_lending.peertopeerloan'),
        ),
    ]
