# Generated by Django 5.2.5 on 2026-02-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact3_lending', '0003_alter_peerloanrepayment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peerloanrepayment',
            old_name='loan',
            new_name='peer_loan',
        ),
    ]
