# Generated by Django 5.2.5 on 2026-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
