# Generated by Django 5.2.5 on 2026-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sjp2_account_last_activity_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersprofile',
            name='national_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
