# Generated by Django 5.2.5 on 2026-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membersprofile_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'SSJP2 Manager'), ('auditor', 'SSJP2  Auditor cheif'), ('customer', 'SSJP2 Members'), ('officer', 'SSJP2  officer '), ('verifier', 'SSJP2 Credit cheif commission'), ('secretary', 'SSJP2 Secretary'), ('itadmin', 'SSJP2 IT Administrator')], default='customer', max_length=20),
        ),
    ]
