# Generated by Django 5.2.5 on 2026-05-27 14:01

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountstatushistory_ended_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankChargesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_bnk_nbr', models.CharField(max_length=30, unique=True)),
                ('bank_name', models.CharField(choices=[('equity_bank', 'Equity Bank'), ('microfinance', 'Microfinance')], default='equity_bank', max_length=30)),
                ('account_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status_type', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('purpose', models.CharField(default='System Charges', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_activity_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
