# Generated by Django 5.2.5 on 2026-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankchargesaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankchargesaccount',
            name='account_bnk_nbr',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
