# Generated by Django 5.2.5 on 2026-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manager', 'Manager'), ('auditor', 'Auditor'), ('customer', 'Customer'), ('officer', 'Officer'), ('verifier', 'Verifier'), ('secretary', 'Secretary'), ('itadmin', 'IT Admin')], max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='accounts.role'),
        ),
    ]
