# Generated by Django 5.2.5 on 2026-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('manager', 'Manager'), ('auditor', 'Auditor'), ('member', 'Member'), ('officer', 'Officer'), ('verifier', 'Verifier'), ('secretary', 'Secretary'), ('itadmin', 'IT Admin')], max_length=20, unique=True),
        ),
    ]
