# Generated by Django 5.2.5 on 2026-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadershipterm',
            name='only_one_active_role',
        ),
        migrations.AlterField(
            model_name='leadershipterm',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
