# Generated by Django 5.2.5 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadershipterm',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
