# Generated by Django 5.2.5 on 2026-04-22 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_remove_user_role_user_roles'),
        ('governance', '0002_alter_election_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leadershipterm',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leadershipterm',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.role'),
        ),
    ]
