# Generated by Django 5.2.5 on 2026-05-11 20:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0001_initial'),
        ('transact5_share_distrib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('flat_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('percent_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_unpaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('due_date', models.DateField(db_index=True)),
                ('monthly_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('delay_time', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_due_transactions', to='accounts.memberaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('receipt_ref_no', models.CharField(blank=True, max_length=12, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='accounts.memberaccount')),
                ('deposit_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='transact1_regular_deposit.depositduetransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SJP2Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('loan_interest', 'Loan Interest'), ('Deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('external_income', 'External Income Source'), ('Expense', 'Expense'), ('interest_distribution', 'Interest Distribution'), ('penalty_late', 'Penalty - Late Payment'), ('penalty_underpayment', 'Penalty - Underpayment'), ('penalty_late_loan', 'Penalty - Late Payment - Loan'), ('penalty_underpayment_loan', 'Penalty - Underpayment - Loan')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('distribution_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_distribute_interest', to='transact5_share_distrib.memberinterestshare')),
                ('expense_purpose', models.ForeignKey(blank=True, help_text='Purpose of the expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.expensepurpose')),
                ('from_member_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='accounts.memberaccount')),
                ('from_sjp2_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_sent_transactions', to='accounts.sjp2_account')),
                ('income_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transactions', to='accounts.incomesource')),
                ('interest_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transact5_share_distrib.yearlyinterestpool')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_member_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='accounts.memberaccount')),
                ('to_sjp2_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_received_transactions', to='accounts.sjp2_account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='accounts.memberaccount')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='accounts.memberaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transactions', to='accounts.memberaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
