# Generated by Django 5.2.5 on 2026-01-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transact1_regular_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='sjp2transaction',
            name='expense_purpose',
        ),
        migrations.RemoveField(
            model_name='sjp2transaction',
            name='from_sjp2_account',
        ),
        migrations.RemoveField(
            model_name='sjp2transaction',
            name='income_source',
        ),
        migrations.RemoveField(
            model_name='sjp2transaction',
            name='to_member_account',
        ),
        migrations.AlterField(
            model_name='depositduetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='from_member_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.memberaccount'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='reference_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transact1_regular_deposit.depositduetransaction'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='to_sjp2_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sjp2_account'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('loan_interest', 'Loan Interest'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('external_income', 'External Income'), ('expense', 'Expense'), ('penalty_late', 'Penalty Late'), ('penalty_underpay', 'Penalty Underpay')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
