# Generated by Django 5.2.5 on 2026-01-22 13:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transact1_regular_deposit', '0002_alter_deposittransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Deposit Transaction', 'verbose_name_plural': 'Deposit Transactions'},
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='expense_purpose',
            field=models.ForeignKey(blank=True, help_text='Purpose of the expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.expensepurpose'),
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='from_sjp2_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_sent_transactions', to='accounts.sjp2_account'),
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='income_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transactions', to='accounts.incomesource'),
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='to_member_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='accounts.memberaccount'),
        ),
        migrations.AlterField(
            model_name='depositduetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='from_member_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='accounts.memberaccount'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='reference_transaction',
            field=models.ForeignKey(blank=True, help_text='Reference to the original deposit due transaction (used for penalties).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_transactions', to='transact1_regular_deposit.depositduetransaction'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='to_sjp2_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_received_transactions', to='accounts.sjp2_account'),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('loan_interest', 'loan-interest'), ('Deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('external_income', 'External Income Source'), ('Expense', 'Expense'), ('penalty_late', 'Penalty - Late Payment'), ('penalty_underpayment', 'Penalty - Underpayment'), ('penalty_late_loan', 'Penalty - Late Payment - Loan'), ('penalty_underpayment_loan', 'Penalty - Underpayment - Loan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
