# Generated by Django 5.2.5 on 2026-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0003_alter_deposittransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={},
        ),
    ]
