# Generated by Django 5.2.5 on 2026-01-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transact1_regular_deposit', '0004_alter_deposittransaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sjp2transaction',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sjp2transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sjp2transaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('loan_interest', 'Loan Interest'), ('Deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('external_income', 'External Income Source'), ('Expense', 'Expense'), ('penalty_late', 'Penalty - Late Payment'), ('penalty_underpayment', 'Penalty - Underpayment'), ('penalty_late_loan', 'Penalty - Late Payment - Loan'), ('penalty_underpayment_loan', 'Penalty - Underpayment - Loan')], max_length=30),
        ),
        migrations.DeleteModel(
            name='DailyOperation',
        ),
    ]
