# Generated by Django 5.2.5 on 2026-03-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('transact1_regular_deposit', '0005_remove_sjp2transaction_reference_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositduetransaction',
            name='paid_on',
        ),
        migrations.RemoveField(
            model_name='depositduetransaction',
            name='receipt_ref_no',
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='receipt_ref_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='depositduetransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_due_transactions', to='accounts.memberaccount'),
        ),
        migrations.AlterField(
            model_name='depositduetransaction',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='accounts.memberaccount'),
        ),
    ]
