# Generated by Django 5.2.5 on 2026-03-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0006_remove_depositduetransaction_paid_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositduetransaction',
            old_name='amount_due',
            new_name='monthly_due',
        ),
    ]
