# Generated by Django 5.2.5 on 2026-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0007_rename_amount_due_depositduetransaction_monthly_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjp2transaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('loan_interest', 'Loan Interest'), ('Deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('external_income', 'External Income Source'), ('Expense', 'Expense'), ('interest_distribution', 'Interest Distribution'), ('penalty_late', 'Penalty - Late Payment'), ('penalty_underpayment', 'Penalty - Underpayment'), ('penalty_late_loan', 'Penalty - Late Payment - Loan'), ('penalty_underpayment_loan', 'Penalty - Underpayment - Loan')], max_length=30),
        ),
    ]
