# Generated by Django 5.2.5 on 2026-05-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0009_sjp2transaction_perfromed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sjp2transaction',
            old_name='perfromed_by',
            new_name='performed_by',
        ),
    ]
