# Generated by Django 5.2.5 on 2026-05-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0010_rename_perfromed_by_sjp2transaction_performed_by'),
        ('transact5_share_distrib', '0002_remove_yearlyinterestpool_is_distributed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjp2transaction',
            name='distribution_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sjp2_distribute_interest', to='transact5_share_distrib.memberinterestshare'),
        ),
    ]
