# Generated by Django 5.2.5 on 2026-05-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact1_regular_deposit', '0011_sjp2transaction_distribution_purpose'),
        ('transact5_share_distrib', '0002_remove_yearlyinterestpool_is_distributed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjp2transaction',
            name='interest_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transact5_share_distrib.yearlyinterestpool'),
        ),
    ]
