# Generated by Django 5.2.5 on 2026-05-11 20:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField(choices=[(3, '3 Months (Emergency)'), (12, '1 Year (Regular)'), (24, '2 Years (Regular)')])),
                ('interest_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('paid', 'Fully Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('issued_on', models.DateField(default=django.utils.timezone.now)),
                ('rejected_reason', models.TextField(blank=True, help_text='Reason for rejecting the loan', null=True)),
                ('rejected_on', models.DateTimeField(blank=True, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.memberaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('top_up_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topups', to='transact2_loans.loan')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request', 'Loan Requested'), ('approve', 'Loan Approved'), ('reject', 'Loan Rejected'), ('disburse', 'Loan Disbursed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transact2_loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('receipt_ref_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('delay_time', models.PositiveIntegerField(default=0, editable=False)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('ledger_posted', models.BooleanField(default=False, editable=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transact2_loans.loan')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='transact2_loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30)),
                ('previous_stage', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30, null=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transact2_loans.loanworkflow')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
