# Generated by Django 5.2.5 on 2026-01-28 12:25

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='delay_time',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
