# Generated by Django 5.2.5 on 2026-05-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0002_loan_rejected_by_alter_loan_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='rejected_on',
            new_name='perfromed_on',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='loan',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
