# Generated by Django 5.2.5 on 2026-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0002_remove_loanpayment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='ledger_posted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
