# Generated by Django 5.2.5 on 2026-05-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0003_rename_rejected_on_loan_perfromed_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='perfromed_on',
            new_name='performed_on',
        ),
    ]
