# Generated by Django 5.2.5 on 2026-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0003_loanpayment_ledger_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the loan', null=True),
        ),
    ]
