# Generated by Django 5.2.5 on 2026-05-27 14:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankchargesaccount'),
        ('transact2_loans', '0004_rename_perfromed_on_loan_performed_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankChargesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=30)),
                ('ledger_posted', models.BooleanField(default=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('from_bank_charge_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='accounts.bankchargesaccount')),
                ('from_member_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_charge_outgoing', to='accounts.memberaccount')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_bank_charge_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='accounts.bankchargesaccount')),
                ('to_member_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_charge_incoming', to='accounts.memberaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['reference'], name='transact2_l_referen_29a1da_idx'), models.Index(fields=['timestamp'], name='transact2_l_timesta_10112a_idx'), models.Index(fields=['transaction_type'], name='transact2_l_transac_f1e3af_idx')],
            },
        ),
    ]
