# Generated by Django 5.2.5 on 2026-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0005_bankchargestransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankchargestransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
