# Generated by Django 5.2.5 on 2026-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0005_loan_approved_on_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
