# Generated by Django 5.2.5 on 2026-05-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0006_bankchargestransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
