# Generated by Django 5.2.5 on 2026-05-07 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0006_alter_loanpayment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='transact2_loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transact2_loans.loanworkflow')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
