# Generated by Django 5.2.5 on 2026-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact2_loans', '0007_loanworkflow_loanworkflowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanworkflowhistory',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('officer_review', 'Officer Review'), ('manager_review', 'Manager Review'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], max_length=30, null=True),
        ),
    ]
